[package]
name = "miranda-storage-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
miranda-core = { path = "../core" }
miranda-storage = { path = "../storage" }

serde_json = { workspace = true }
sqlx = { workspace = true, features = ["postgres"] }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
