[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
async-trait = { version = "0.1.91" }
clap = { version = "4.6.6", features = ["derive", "env"] }
dirs = { version = "6.0.0" }
futures-util = { version = "0.3.33" }
reqwest = { version = "0.13.4", features = ["json", "query"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
sqlx = { version = "0.9.0", features = [
  "runtime-tokio",
  "tls-rustls",
  "uuid",
  "json",
  "macros",
  "migrate",
] }
time = { version = "0.3.55", features = ["parsing"] }
thiserror = { version = "2.0.19" }
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = { version = "0.7.19" }
tracing = { version = "0.1.44" }
tracing-subscriber = { version = "0.3.23" }
url = { version = "2.5.8" }
uuid = { version = "1.24.0", features = ["serde", "v4", "v7"] }
yaml_serde = { version = "0.10.4" }
