[package]
name = "miranda-storage-sqlite"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
miranda-core = { path = "../core" }
miranda-storage = { path = "../storage" }

thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["sqlite"] }
