[package]
name = "miranda-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
miranda-core = { path = "../core", features = ["spec"] }
miranda-engine = { path = "../engine" }
miranda-storage = { path = "../storage" }
miranda-storage-mysql = { path = "../storage-mysql" }
miranda-storage-postgres = { path = "../storage-postgres" }
miranda-storage-sqlite = { path = "../storage-sqlite" }
miranda-worker = { path = "../worker" }

clap = { workspace = true }
dirs = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
wiremock = { workspace = true }
