blank_issues_enabled: false
contact_links:
  - name: 🔒 Report a security vulnerability
    url: https://github.com/rafiandria23/miranda/security/advisories/new
    about: Please report security issues privately rather than opening a public issue.
  - name: ❓ Questions & support
    url: https://github.com/rafiandria23/miranda/discussions
    about: For usage questions that aren't a bug or feature request.
