[package]
name = "miranda-control-plane"
version = "0.1.0"
edition = "2024"

[dependencies]
miranda-core = { path = "../core" }
miranda-engine = { path = "../engine" }
miranda-storage = { path = "../storage" }
miranda-worker = { path = "../worker" }

thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
