[package]
name = "miranda-control-plane"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
miranda-core = { path = "../core" }
miranda-engine = { path = "../engine" }
miranda-storage = { path = "../storage" }
miranda-worker = { path = "../worker" }

thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
